include ../common.mk

.PHONY: all clean

all:
	@echo "In subdir1:"
	@echo "Compiler: $(CC)"
	@echo "Flags:    $(CFLAGS)"
	@echo "FOO var:  $(FOO)"
	@echo "FIX var:  $(FIX_VAL)"
	@echo "EX SHARE: $(EX_VAL)"

clean:
	@echo "Cleaning subdir1"

